### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [javamanatee/thomas-hardy_a-pair-of-blue-eyes#1]
### General Issues:

- [x] Re-run `se clean .` and commit the changes.

- [x] Re-run `se semanticate .` and commit most of the changes.

### dramatis-personae.xhtml:

- [x] `<p>Other servants, masons, labourers, grooms, nondescripts, <abbr>etc.</abbr>, <abbr class="eoc">etc.</abbr></p>` should be included in the list.

- [x] Remove  `epub:type="z3998:subsection"`. This semantic is for file `<section>`s / `<article>`s.

- [x] Place `<p>The Scene</p><p>Mostly on the outskirts of Lower Wessex.</p>` in a `<section>` element and `<p>The Scene</p>` in a `<header>` element.

- [x] The personas should be sentence-cased.

### chapter-2.xhtml:

- [x] Remove `epub:type="z3998:subsection"`.

- [x] `<p>1.⁠—<abbr>Mr.</abbr> Swancourt to <abbr>Mr.</abbr> Hewby.</p>` and `<p>2.⁠—<abbr>Mr.</abbr> Hewby to <abbr>Mr.</abbr> Swancourt.</p>` should be included in the letter headers. You can add `<b>` to apply small caps, centering, and margins.

### chapter-4.xhtml:

- [x] In `sloping down together like the letter V` tag the V with `<i epub:type="z3998:grapheme">`.

### chapter-9.xhtml:

- [x] The lint error in this chapter looks like a false flag. Create an `se-lint-ignore.xml` file for this error ([SEMOS 2.3](https://standardebooks.org/manual/1.7.0/single-page#2.3)).

### chapter-12.xhtml:

- [x] Remove `epub:type="z3998:subsection"`.

- [x] `<p>Right Hand.</p>` and `<p>Left Hand.</p>` should be inside the `<blockquote>`s and in `<header>` elements. Remove the trailing periods.

### chapter-18.xhtml:

- [x] For `<abbr><em>Mem.</em></abbr>`, move `<abbr>` inside the `<em>` element.

### chapter-31.xhtml:

- [x] Remove the quotes around Paradise Lost and tag it with `<i epub:type="se:name.publication.poem">`.

### endnotes.xhtml:

- [x] The note needs a link to the preface. See [SEMOS 5.1.2.8](https://standardebooks.org/manual/1.7.0/single-page#5.1.2.8).

### local.css:

- [x] Add epigraph CSS ([SEMOS 7.4.6.3](https://standardebooks.org/manual/1.7.0/single-page#7.4.6.3)).

- [x] Add dramatis personae CSS ([SEMOS 7.6.74](https://standardebooks.org/manual/1.7.0/single-page#7.6.7.4)).

- [x] Add header CSS ([SEMOS 7.2.10.8](https://standardebooks.org/manual/1.7.0/single-page#7.2.10.8)).

- [x] Replace `body [xml|lang]` with `blockquote[xml|lang]`.

### content.opf:

- [x] There's a typo is the short description (`engageed`).

- [x] Replace the IA link with [https://archive.org/details/pairofblueeyes00hard_0](https://archive.org/details/pairofblueeyes00hard_0).

- [x] The production note is not needed. It is very common to have editions with slight changes.

### colophon.xhtml:

- [x] Replace the IA link with [https://archive.org/details/pairofblueeyes00hard_0](https://archive.org/details/pairofblueeyes00hard_0).

### imprint.xhtml:

- [x] Replace the IA link with [https://archive.org/details/pairofblueeyes00hard_0](https://archive.org/details/pairofblueeyes00hard_0).

**Comment by javamanatee** [comment]
I'm working through the issues and have a few comments/questions.

For grapheme, there is also a letter Z in the same chapter:  "the chair, like the letter Z..." but this one is spoken. Should I apply grapheme or phoneme to that one?

The header styling put all headers into small caps, so I added a font-variant: normal on chapter epigraphs and letter headers, to keep them the way they were.  The letter headers are mainly datelines, but I don't know that they require the small caps style.

In dramatis personae, "The Scene" in header keeps it close to preceding list, but rather far from the scene description.  So I applied some margin to just that header, to group it better.

**Comment by EmmaSweeney** [comment]
> For grapheme, there is also a letter Z in the same chapter: "the chair, like the letter Z..." but this one is spoken. Should I apply grapheme or phoneme to that one?

Use grapheme.

> The header styling put all headers into small caps, so I added a font-variant: normal on chapter epigraphs and letter headers, to keep them the way they were. The letter headers are mainly datelines, but I don't know that they require the small caps style.
> 
> In dramatis personae, "The Scene" in header keeps it close to preceding list, but rather far from the scene description. So I applied some margin to just that header, to group it better.

After you make all the changes, I'll be reviewing the CSS again.

**Comment by javamanatee** [comment]
I think I got it all.  Ready for review again.
